# Generated by Django 4.2.2 on 2023-07-05 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_alter_review_restaurant'),
        ('comment', '0002_remove_comment_review_comment_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.review'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
