# Generated by Django 4.2.2 on 2023-07-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_review_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
