# Generated by Django 4.2.2 on 2023-07-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_modified',
        ),
    ]
