# Generated by Django 4.2.2 on 2023-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_remove_comment_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
