# Generated by Django 4.2.2 on 2023-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
