# Generated by Django 4.2.2 on 2023-07-03 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(blank=True, max_length=9, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.CharField(max_length=100)),
                ('price_level', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=1)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurant.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating_average', models.FloatField(blank=True, default=0, null=True)),
                ('review_count', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
