# Generated by Django 4.2.2 on 2023-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
