# Generated by Django 4.2.2 on 2023-07-06 12:28

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_email_alter_restaurant_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.models.user_directory_path),
        ),
    ]
